language: python

dist: trusty

matrix:
  include:
    - python: 'pypy'
      env: TOXENV=pypy
    - python: 'pypy3'
      env: TOXENV=pypy3
    - python: '3.6'
      env: TOXENV=py36
    - python: '3.6'
      env: TOXENV=pylama

install:
  - pip install tox coveralls

script:
  - tox

services:
  - memcached

sudo: required

after_success:
  - coveralls
